
'use server';
/**
 * @fileOverview An AI document assistant that uses RAG to answer questions.
 *
 * - documentAssistant - A function that answers questions based on document content.
 * - DocumentAssistantInput - The input type for the documentAssistant function.
 * - DocumentAssistantOutput - The return type for the documentAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import * as fs from 'fs/promises';
import * as path from 'path';

// Define a tool for the AI to get document content.
const getDocumentContent = ai.defineTool(
  {
    name: 'getDocumentContent',
    description: 'Retrieves the content of a specified document from the knowledge base.',
    inputSchema: z.object({
      documentName: z.string().describe('The name of the document to retrieve, e.g., "PNT-Melt-Index.txt"'),
    }),
    outputSchema: z.string(),
  },
  async ({documentName}) => {
    try {
      // In a real app, this would fetch from a secure storage like Firebase Storage.
      // For this demo, we'll read from the local /public/data directory.
      const filePath = path.join(process.cwd(), 'public', 'data', documentName);
      const content = await fs.readFile(filePath, 'utf-8');
      return content;
    } catch (error) {
      console.error(`Failed to read document: ${documentName}`, error);
      return `Error: Could not retrieve the document named ${documentName}. Please ensure the name is correct.`;
    }
  }
);


const DocumentAssistantInputSchema = z.object({
  prompt: z.string().describe("The user's question about a procedure or document."),
});
export type DocumentAssistantInput = z.infer<typeof DocumentAssistantInputSchema>;

const DocumentAssistantOutputSchema = z.object({
  response: z.string().describe('The answer generated by the AI based on the document content.'),
});
export type DocumentAssistantOutput = z.infer<typeof DocumentAssistantOutputSchema>;

export async function documentAssistant(input: DocumentAssistantInput): Promise<DocumentAssistantOutput> {
  return documentAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'documentAssistantPrompt',
  input: {schema: DocumentAssistantInputSchema},
  output: {schema: DocumentAssistantOutputSchema},
  tools: [getDocumentContent],
  prompt: `You are an expert assistant for the PoliLIMS laboratory. Your role is to answer questions based *only* on the content of the provided documents.

  The user has asked a question. Follow these steps:
  1. Use the 'getDocumentContent' tool to retrieve the content of the relevant document(s). For now, assume the relevant document is 'PNT-Melt-Index.txt' if the user asks about Melt Index or MFI.
  2. Analyze the retrieved document content.
  3. Formulate a clear, concise, and accurate answer to the user's question based *exclusively* on the information from the document.
  4. If the document does not contain the answer, state that the information is not available in the provided document. Do not use your general knowledge.

  User's Question: {{{prompt}}}
  `,
});

const documentAssistantFlow = ai.defineFlow(
  {
    name: 'documentAssistantFlow',
    inputSchema: DocumentAssistantInputSchema,
    outputSchema: DocumentAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
