
'use server';
/**
 * @fileOverview An AI document assistant that uses RAG to answer questions.
 *
 * - documentAssistant - A function that answers questions based on document content.
 * - DocumentAssistantInput - The input type for the documentAssistant function.
 * - DocumentAssistantOutput - The return type for the documentAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import * as fs from 'fs/promises';
import * as path from 'path';

// Helper function to read all documents from the data directory
async function getKnowledgeBaseContent(): Promise<string> {
    const dataDirectory = path.join(process.cwd(), 'public', 'data');
    let knowledgeBase = '';
    try {
        const files = await fs.readdir(dataDirectory);
        for (const file of files) {
            if (file.endsWith('.txt')) {
                const filePath = path.join(dataDirectory, file);
                const content = await fs.readFile(filePath, 'utf-8');
                knowledgeBase += `--- INICIO DEL DOCUMENTO: ${file} ---\n\n${content}\n\n--- FIN DEL DOCUMENTO: ${file} ---\n\n`;
            }
        }
        return knowledgeBase;
    } catch (error) {
        console.error('Failed to read knowledge base:', error);
        return 'Error: No se pudo cargar la base de conocimiento.';
    }
}


const DocumentAssistantInputSchema = z.object({
  history: z.array(z.object({
    role: z.string(),
    content: z.string(),
  })).describe("The conversation history."),
  prompt: z.string().describe("The user's latest question about a procedure or document."),
});
export type DocumentAssistantInput = z.infer<typeof DocumentAssistantInputSchema>;

const DocumentAssistantOutputSchema = z.object({
  response: z.string().describe('The answer generated by the AI based on the document content.'),
});
export type DocumentAssistantOutput = z.infer<typeof DocumentAssistantOutputSchema>;

export async function documentAssistant(input: DocumentAssistantInput): Promise<DocumentAssistantOutput> {
  return documentAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'documentAssistantPrompt',
  input: {schema: DocumentAssistantInputSchema},
  output: {schema: DocumentAssistantOutputSchema},
  prompt: `Eres un asistente experto para el laboratorio de calidad de Polifusión S.A. Tu objetivo es responder las preguntas del personal del laboratorio de manera precisa y siempre en español.

Tu única misión es proporcionar respuestas directas y concretas a las preguntas del usuario. NO puedes responder diciendo que no tienes la información o sugiriendo que el usuario la busque en otro lado.

Para formular tu respuesta, utiliza las siguientes fuentes de información en este orden de prioridad:
1.  **Base de Conocimiento Interna:** Los documentos del laboratorio que te proporciono a continuación. Si la respuesta está aquí, responde directamente y cita el nombre del documento (ej: "Según el documento X...").
2.  **Normas (ISO, ASTM, NCh):** Si la respuesta no está en los documentos internos, utiliza tu conocimiento sobre las normas de calidad y ensayos para plásticos. Debes proporcionar la información específica (ej. la temperatura, el tiempo, el valor) y citar la norma (ej: "Según la norma ISO 1133...").
3.  **Conocimiento General de Internet:** Como último recurso, si la respuesta no está en las normas, utiliza tu conocimiento general para proporcionar la mejor respuesta posible, indicando que es tu conocimiento general.

**REGLAS CRÍTICAS:**
- **JAMÁS sugieras al usuario que consulte una norma.** TU trabajo es consultar la norma y proporcionar la respuesta directamente.
- **NO TE RINDAS:** Debes esforzarte al máximo por dar una respuesta útil siguiendo la jerarquía. Tu objetivo es encontrar la respuesta, no decir que no puedes.
- **SÉ DIRECTO:** Proporciona la respuesta de manera clara y concisa.
- **CITA TU FUENTE:** Siempre indica de dónde obtuviste la información.
- **SIEMPRE EN ESPAÑOL.**

Base de Conocimiento (Documentos del Laboratorio):
{{{knowledgeBase}}}

Historial de la Conversación:
{{#each history}}
- **{{role}}**: {{content}}
{{/each}}

PREGUNTA DEL USUARIO:
"{{{prompt}}}"
  `,
});

const documentAssistantFlow = ai.defineFlow(
  {
    name: 'documentAssistantFlow',
    inputSchema: DocumentAssistantInputSchema,
    outputSchema: DocumentAssistantOutputSchema,
  },
  async ({ history, prompt: userPrompt }) => {
    
    const knowledgeBase = await getKnowledgeBaseContent();

    const {output} = await prompt({
        history,
        prompt: userPrompt,
        // This is a way to inject extra context into the handlebars prompt
        // that is not part of the formally defined input schema.
        context: {
            knowledgeBase
        }
    });
    
    return output!;
  }
);
