
'use server';
/**
 * @fileOverview An AI document assistant that uses RAG to answer questions.
 *
 * - documentAssistant - A function that answers questions based on document content.
 * - DocumentAssistantInput - The input type for the documentAssistant function.
 * - DocumentAssistantOutput - The return type for the documentAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import * as fs from 'fs/promises';
import * as path from 'path';

const dataDirectory = path.join(process.cwd(), 'public', 'data');

// Define a tool for the AI to list available documents.
const listAvailableDocuments = ai.defineTool(
  {
    name: 'listAvailableDocuments',
    description: 'Lists the available documents in the knowledge base.',
    inputSchema: z.object({}),
    outputSchema: z.array(z.string()),
  },
  async () => {
    try {
      const files = await fs.readdir(dataDirectory);
      return files.filter(file => file.endsWith('.txt'));
    } catch (error) {
      console.error('Failed to list documents:', error);
      return ['Error: Could not retrieve the list of documents.'];
    }
  }
);


// Define a tool for the AI to get document content.
const getDocumentContent = ai.defineTool(
  {
    name: 'getDocumentContent',
    description: 'Retrieves the content of a specified document from the knowledge base.',
    inputSchema: z.object({
      documentName: z.string().describe('The name of the document to retrieve, e.g., "PNT-Melt-Index.txt"'),
    }),
    outputSchema: z.string(),
  },
  async ({documentName}) => {
    try {
      // In a real app, this would fetch from a secure storage like Firebase Storage.
      // For this demo, we'll read from the local /public/data directory.
      const filePath = path.join(dataDirectory, documentName);
      const content = await fs.readFile(filePath, 'utf-8');
      return content;
    } catch (error) {
      console.error(`Failed to read document: ${documentName}`, error);
      return `Error: Could not retrieve the document named ${documentName}. Please ensure the name is correct.`;
    }
  }
);


const DocumentAssistantInputSchema = z.object({
  prompt: z.string().describe("The user's question about a procedure or document."),
});
export type DocumentAssistantInput = z.infer<typeof DocumentAssistantInputSchema>;

const DocumentAssistantOutputSchema = z.object({
  response: z.string().describe('The answer generated by the AI based on the document content.'),
});
export type DocumentAssistantOutput = z.infer<typeof DocumentAssistantOutputSchema>;

export async function documentAssistant(input: DocumentAssistantInput): Promise<DocumentAssistantOutput> {
  return documentAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'documentAssistantPrompt',
  input: {schema: DocumentAssistantInputSchema},
  output: {schema: DocumentAssistantOutputSchema},
  tools: [getDocumentContent, listAvailableDocuments],
  prompt: `You are an expert assistant for the PoliLIMS laboratory. Your role is to answer questions based *only* on the content of the provided documents.

  The user has asked a question. Follow these steps:
  1. Use the 'listAvailableDocuments' tool to see which documents are available.
  2. Based on the user's question and the list of documents, determine which document is most likely to contain the answer.
  3. Use the 'getDocumentContent' tool to retrieve the content of that specific document.
  4. Analyze the retrieved document content.
  5. Formulate a clear, concise, and accurate answer to the user's question based *exclusively* on the information from the document.
  6. If the documents do not contain the answer, state that the information is not available in the provided knowledge base. Do not use your general knowledge.

  User's Question: {{{prompt}}}
  `,
});

const documentAssistantFlow = ai.defineFlow(
  {
    name: 'documentAssistantFlow',
    inputSchema: DocumentAssistantInputSchema,
    outputSchema: DocumentAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
