# Generated by Django 5.2.5 on 2025-08-21 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa'), ('seguimiento', 'Seguimiento'), ('certificacion', 'Certificación')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('alcance', models.TextField(verbose_name='Alcance')),
                ('objetivos', models.TextField(verbose_name='Objetivos')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('equipo_auditor', models.JSONField(blank=True, default=list, verbose_name='Equipo Auditor')),
                ('hallazgos', models.JSONField(blank=True, default=list, verbose_name='Hallazgos')),
                ('no_conformidades', models.JSONField(blank=True, default=list, verbose_name='No Conformidades')),
                ('observaciones', models.JSONField(blank=True, default=list, verbose_name='Observaciones')),
                ('plan_auditoria', models.FileField(blank=True, null=True, upload_to='auditorias/planes/', verbose_name='Plan de Auditoría')),
                ('reporte_auditoria', models.FileField(blank=True, null=True, upload_to='auditorias/reportes/', verbose_name='Reporte de Auditoría')),
                ('evidencias', models.JSONField(blank=True, default=list, verbose_name='Evidencias')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('auditor_lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_calidad_lideradas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Líder')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='CondicionAmbiental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura (°C)')),
                ('humedad', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Humedad (%)')),
                ('presion_atmosferica', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Presión Atmosférica (hPa)')),
                ('equipo_medicion', models.CharField(blank=True, max_length=100, verbose_name='Equipo de Medición')),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Medición')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condiciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Condición Ambiental',
                'verbose_name_plural': 'Condiciones Ambientales',
                'ordering': ['-fecha_medicion'],
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('ensayo', 'Ensayo'), ('equipo', 'Equipo'), ('proveedor', 'Proveedor'), ('proceso', 'Proceso'), ('documentacion', 'Documentación'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_analisis', 'En Análisis'), ('accion_correctiva', 'Acción Correctiva'), ('verificacion', 'En Verificación'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Detección')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('causa_raiz', models.TextField(blank=True, verbose_name='Causa Raíz')),
                ('impacto', models.TextField(blank=True, verbose_name='Impacto')),
                ('accion_correctiva', models.TextField(blank=True, verbose_name='Acción Correctiva')),
                ('accion_preventiva', models.TextField(blank=True, verbose_name='Acción Preventiva')),
                ('verificacion_efectividad', models.TextField(blank=True, verbose_name='Verificación de Efectividad')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Estimado')),
                ('evidencias', models.JSONField(blank=True, default=list, verbose_name='Evidencias')),
                ('documentos', models.JSONField(blank=True, default=list, verbose_name='Documentos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncs_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncs_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncs_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'No Conformidad',
                'verbose_name_plural': 'No Conformidades',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('verificada', 'Verificada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('evidencias', models.JSONField(blank=True, default=list, verbose_name='Evidencias')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('no_conformidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_correctivas', to='calidad.noconformidad', verbose_name='No Conformidad')),
            ],
            options={
                'verbose_name': 'Acción Correctiva',
                'verbose_name_plural': 'Acciones Correctivas',
                'ordering': ['-created_at'],
            },
        ),
    ]
