export interface TipoProducto {
  producto: string;
  material: 'PE100' | 'PP' | 'PP-RCT/FV';
  diametro_nominal: number;
  presion_nominal: string;
  sdr: string;
  diametro_min: number;
  diametro_max: number;
  espesor_min_norma: number;
  espesor_max_norma: number;
  ovalidad_norma: number | null;
  peso_min_teorico: number;
  peso_max_teorico: number;
  presion_phi: number | null;
  temperatura_phi: number | null;
  tiempo_phi: number | null;
  color_tuberia?: string;
  color_linea?: string;
}

export const matrizProductos: TipoProducto[] = [
  {
    producto: "Tuberia PEAD 20 mm PN10",
    material: "PE100",
    diametro_nominal: 20,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 20.0,
    diametro_max: 20.3,
    espesor_min_norma: 2.0,
    espesor_max_norma: 2.4,
    ovalidad_norma: 1.2,
    peso_min_teorico: 0.101,
    peso_max_teorico: 0.129,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 25 mm PN10",
    material: "PE100",
    diametro_nominal: 25,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 25.0,
    diametro_max: 25.3,
    espesor_min_norma: 2.0,
    espesor_max_norma: 2.4,
    ovalidad_norma: 1.2,
    peso_min_teorico: 0.128,
    peso_max_teorico: 0.163,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 32 mm PN10",
    material: "PE100",
    diametro_nominal: 32,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 32.0,
    diametro_max: 32.3,
    espesor_min_norma: 2.0,
    espesor_max_norma: 2.4,
    ovalidad_norma: 1.3,
    peso_min_teorico: 0.167,
    peso_max_teorico: 0.212,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 40 mm PN10",
    material: "PE100",
    diametro_nominal: 40,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 40.0,
    diametro_max: 40.4,
    espesor_min_norma: 2.4,
    espesor_max_norma: 2.8,
    ovalidad_norma: 1.4,
    peso_min_teorico: 0.262,
    peso_max_teorico: 0.334,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 50 mm PN10",
    material: "PE100",
    diametro_nominal: 50,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 50.0,
    diametro_max: 50.4,
    espesor_min_norma: 3.0,
    espesor_max_norma: 3.5,
    ovalidad_norma: 1.5,
    peso_min_teorico: 0.413,
    peso_max_teorico: 0.526,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 63 mm PN10",
    material: "PE100",
    diametro_nominal: 63,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 63.0,
    diametro_max: 63.4,
    espesor_min_norma: 3.8,
    espesor_max_norma: 4.4,
    ovalidad_norma: 2.2,
    peso_min_teorico: 0.655,
    peso_max_teorico: 0.834,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 75 mm PN10",
    material: "PE100",
    diametro_nominal: 75,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 75.0,
    diametro_max: 75.5,
    espesor_min_norma: 4.5,
    espesor_max_norma: 5.1,
    ovalidad_norma: 2.6,
    peso_min_teorico: 0.925,
    peso_max_teorico: 1.178,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 90 mm PN10",
    material: "PE100",
    diametro_nominal: 90,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 90.0,
    diametro_max: 90.6,
    espesor_min_norma: 5.4,
    espesor_max_norma: 6.1,
    ovalidad_norma: 3.2,
    peso_min_teorico: 1.328,
    peso_max_teorico: 1.691,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PEAD 110 mm PN10",
    material: "PE100",
    diametro_nominal: 110,
    presion_nominal: "PN10",
    sdr: "SDR 17",
    diametro_min: 110.0,
    diametro_max: 110.7,
    espesor_min_norma: 6.6,
    espesor_max_norma: 7.4,
    ovalidad_norma: 3.9,
    peso_min_teorico: 1.990,
    peso_max_teorico: 2.535,
    presion_phi: 35,
    temperatura_phi: 80,
    tiempo_phi: 165,
    color_tuberia: "Negro",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia PP-R 20 mm PN20",
    material: "PP",
    diametro_nominal: 20,
    presion_nominal: "PN20",
    sdr: "SDR 6",
    diametro_min: 20.0,
    diametro_max: 20.3,
    espesor_min_norma: 3.4,
    espesor_max_norma: 3.9,
    ovalidad_norma: 1.2,
    peso_min_teorico: 0.171,
    peso_max_teorico: 0.218,
    presion_phi: 51,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Verde",
    color_linea: "N/A"
  },
  {
    producto: "Tuberia PP-R 25 mm PN20",
    material: "PP",
    diametro_nominal: 25,
    presion_nominal: "PN20",
    sdr: "SDR 6",
    diametro_min: 25.0,
    diametro_max: 25.3,
    espesor_min_norma: 4.2,
    espesor_max_norma: 4.8,
    ovalidad_norma: 1.2,
    peso_min_teorico: 0.265,
    peso_max_teorico: 0.337,
    presion_phi: 51,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Verde",
    color_linea: "N/A"
  },
  {
    producto: "Tuberia PP-R 32 mm PN20",
    material: "PP",
    diametro_nominal: 32,
    presion_nominal: "PN20",
    sdr: "SDR 6",
    diametro_min: 32.0,
    diametro_max: 32.3,
    espesor_min_norma: 5.4,
    espesor_max_norma: 6.1,
    ovalidad_norma: 1.3,
    peso_min_teorico: 0.428,
    peso_max_teorico: 0.545,
    presion_phi: 51,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Verde",
    color_linea: "N/A"
  },
  {
    producto: "Tuberia FASER BETA-FIBRA 20 mm PN20",
    material: "PP-RCT/FV",
    diametro_nominal: 20,
    presion_nominal: "PN20",
    sdr: "SDR 7,4",
    diametro_min: 20.0,
    diametro_max: 20.3,
    espesor_min_norma: 2.8,
    espesor_max_norma: 3.2,
    ovalidad_norma: null,
    peso_min_teorico: 0.155,
    peso_max_teorico: 0.180,
    presion_phi: 53,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Blanco",
    color_linea: "Roja"
  },
  {
    producto: "Tuberia FASER AQUA-FIBRA 20 mm PN20",
    material: "PP-RCT/FV",
    diametro_nominal: 20,
    presion_nominal: "PN20",
    sdr: "SDR 7,4",
    diametro_min: 20.0,
    diametro_max: 20.3,
    espesor_min_norma: 2.8,
    espesor_max_norma: 3.2,
    ovalidad_norma: null,
    peso_min_teorico: 0.155,
    peso_max_teorico: 0.180,
    presion_phi: 53,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Verde",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia FASER BETA-FIBRA 25 mm PN20",
    material: "PP-RCT/FV",
    diametro_nominal: 25,
    presion_nominal: "PN20",
    sdr: "SDR 7,4",
    diametro_min: 25.0,
    diametro_max: 25.3,
    espesor_min_norma: 3.5,
    espesor_max_norma: 4.0,
    ovalidad_norma: null,
    peso_min_teorico: 0.237,
    peso_max_teorico: 0.276,
    presion_phi: 53,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Blanco",
    color_linea: "Roja"
  },
  {
    producto: "Tuberia FASER AQUA-FIBRA 25 mm PN20",
    material: "PP-RCT/FV",
    diametro_nominal: 25,
    presion_nominal: "PN20",
    sdr: "SDR 7,4",
    diametro_min: 25.0,
    diametro_max: 25.3,
    espesor_min_norma: 3.5,
    espesor_max_norma: 4.0,
    ovalidad_norma: null,
    peso_min_teorico: 0.237,
    peso_max_teorico: 0.276,
    presion_phi: 53,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Verde",
    color_linea: "Azul"
  },
  {
    producto: "Tuberia FASER BETA-FIBRA 32 mm PN20",
    material: "PP-RCT/FV",
    diametro_nominal: 32,
    presion_nominal: "PN20",
    sdr: "SDR 7,4",
    diametro_min: 32.0,
    diametro_max: 32.3,
    espesor_min_norma: 4.4,
    espesor_max_norma: 5.0,
    ovalidad_norma: null,
    peso_min_teorico: 0.377,
    peso_max_teorico: 0.439,
    presion_phi: 53,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Blanco",
    color_linea: "Roja"
  },
  {
    producto: "Tuberia FASER AQUA-FIBRA 32 mm PN20",
    material: "PP-RCT/FV",
    diametro_nominal: 32,
    presion_nominal: "PN20",
    sdr: "SDR 7,4",
    diametro_min: 32.0,
    diametro_max: 32.3,
    espesor_min_norma: 4.4,
    espesor_max_norma: 5.0,
    ovalidad_norma: null,
    peso_min_teorico: 0.377,
    peso_max_teorico: 0.439,
    presion_phi: 53,
    temperatura_phi: 95,
    tiempo_phi: 22,
    color_tuberia: "Verde",
    color_linea: "Azul"
  }
];
