export interface TipoProducto {
  producto: string;
  material: 'PE100' | 'PP' | 'PP-RCT/FV' | 'PEAD' | 'PPR' | 'PP-R' | 'PPR-CT' | 'PPR-CT/FV' | 'PP-RCT';
  diametro_nominal: number;
  presion_nominal: string;
  sdr: string;
  diametro_min: number;
  diametro_max: number;
  espesor_min_norma: number;
  espesor_max_norma: number;
  ovalidad_norma: number | null;
  peso_min_teorico: number;
  peso_max_teorico: number;
  presion_phi: number | null;
  temperatura_phi: number | null;
  tiempo_phi: number | null;
  color_tuberia?: string;
  color_linea?: string;
}

export const matrizProductos: TipoProducto[] = [
    {
        "producto": "Tuberia PEAD 20 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 20,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 20.0,
        "diametro_max": 20.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.043,
        "peso_max_teorico": 0.057,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 25 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 25,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 25.0,
        "diametro_max": 25.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.054,
        "peso_max_teorico": 0.071,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 32 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 32,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 32.0,
        "diametro_max": 32.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.3,
        "peso_min_teorico": 0.070,
        "peso_max_teorico": 0.091,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 40 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 40,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 40.0,
        "diametro_max": 40.4,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.4,
        "peso_min_teorico": 0.088,
        "peso_max_teorico": 0.115,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 50 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 50,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 50.0,
        "diametro_max": 50.4,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.5,
        "peso_min_teorico": 0.111,
        "peso_max_teorico": 0.144,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 63 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 63,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 63.0,
        "diametro_max": 63.4,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 2.2,
        "peso_min_teorico": 0.141,
        "peso_max_teorico": 0.183,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 75 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 75,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 2.6,
        "peso_min_teorico": 0.168,
        "peso_max_teorico": 0.218,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 90 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 90,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 90.0,
        "diametro_max": 90.6,
        "espesor_min_norma": 2.2,
        "espesor_max_norma": 2.6,
        "ovalidad_norma": 3.2,
        "peso_min_teorico": 0.222,
        "peso_max_teorico": 0.287,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 110 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 110,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 110.0,
        "diametro_max": 110.7,
        "espesor_min_norma": 2.7,
        "espesor_max_norma": 3.2,
        "ovalidad_norma": 3.9,
        "peso_min_teorico": 0.334,
        "peso_max_teorico": 0.432,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 125 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 125,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 125.0,
        "diametro_max": 125.8,
        "espesor_min_norma": 3.1,
        "espesor_max_norma": 3.6,
        "ovalidad_norma": 4.4,
        "peso_min_teorico": 0.437,
        "peso_max_teorico": 0.565,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 140 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 140,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 140.0,
        "diametro_max": 140.9,
        "espesor_min_norma": 3.5,
        "espesor_max_norma": 4.1,
        "ovalidad_norma": 4.9,
        "peso_min_teorico": 0.552,
        "peso_max_teorico": 0.714,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 160 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 160,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 160.0,
        "diametro_max": 161.0,
        "espesor_min_norma": 3.9,
        "espesor_max_norma": 4.5,
        "ovalidad_norma": 5.6,
        "peso_min_teorico": 0.706,
        "peso_max_teorico": 0.912,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 180 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 180,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 180.0,
        "diametro_max": 181.1,
        "espesor_min_norma": 4.4,
        "espesor_max_norma": 5.0,
        "ovalidad_norma": 6.3,
        "peso_min_teorico": 0.895,
        "peso_max_teorico": 1.155,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 200 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 200,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 200.0,
        "diametro_max": 201.2,
        "espesor_min_norma": 4.9,
        "espesor_max_norma": 5.6,
        "ovalidad_norma": 7.0,
        "peso_min_teorico": 1.104,
        "peso_max_teorico": 1.426,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 225 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 225,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 225.0,
        "diametro_max": 226.4,
        "espesor_min_norma": 5.5,
        "espesor_max_norma": 6.3,
        "ovalidad_norma": 7.9,
        "peso_min_teorico": 1.396,
        "peso_max_teorico": 1.802,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 250 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 250,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 250.0,
        "diametro_max": 251.5,
        "espesor_min_norma": 6.1,
        "espesor_max_norma": 7.0,
        "ovalidad_norma": 8.8,
        "peso_min_teorico": 1.722,
        "peso_max_teorico": 2.223,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 280 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 280,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 280.0,
        "diametro_max": 281.7,
        "espesor_min_norma": 6.9,
        "espesor_max_norma": 7.9,
        "ovalidad_norma": 9.8,
        "peso_min_teorico": 2.175,
        "peso_max_teorico": 2.808,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 315 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 315,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 315.0,
        "diametro_max": 316.9,
        "espesor_min_norma": 7.7,
        "espesor_max_norma": 8.8,
        "ovalidad_norma": 11.0,
        "peso_min_teorico": 2.731,
        "peso_max_teorico": 3.526,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 355 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 355,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 355.0,
        "diametro_max": 357.1,
        "espesor_min_norma": 8.7,
        "espesor_max_norma": 9.9,
        "ovalidad_norma": 12.4,
        "peso_min_teorico": 3.476,
        "peso_max_teorico": 4.488,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 400 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 400,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 400.0,
        "diametro_max": 402.4,
        "espesor_min_norma": 9.8,
        "espesor_max_norma": 11.2,
        "ovalidad_norma": 14.0,
        "peso_min_teorico": 4.417,
        "peso_max_teorico": 5.704,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 450 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 450,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 450.0,
        "diametro_max": 452.7,
        "espesor_min_norma": 11.0,
        "espesor_max_norma": 12.5,
        "ovalidad_norma": 15.8,
        "peso_min_teorico": 5.578,
        "peso_max_teorico": 7.199,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 500 mm PN4",
        "material": "PEAD",
        "diametro_nominal": 500,
        "presion_nominal": "PN4",
        "sdr": "SDR 41",
        "diametro_min": 500.0,
        "diametro_max": 503.0,
        "espesor_min_norma": 12.2,
        "espesor_max_norma": 13.9,
        "ovalidad_norma": 17.5,
        "peso_min_teorico": 6.866,
        "peso_max_teorico": 8.865,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 20 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 20,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 20.0,
        "diametro_max": 20.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.065,
        "peso_max_teorico": 0.086,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 25 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 25,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 25.0,
        "diametro_max": 25.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.082,
        "peso_max_teorico": 0.108,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 32 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 32,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 32.0,
        "diametro_max": 32.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.3,
        "peso_min_teorico": 0.107,
        "peso_max_teorico": 0.140,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 40 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 40,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 40.0,
        "diametro_max": 40.4,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.4,
        "peso_min_teorico": 0.135,
        "peso_max_teorico": 0.176,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 50 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 50,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 50.0,
        "diametro_max": 50.4,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.5,
        "peso_min_teorico": 0.170,
        "peso_max_teorico": 0.221,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 63 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 63,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 63.0,
        "diametro_max": 63.4,
        "espesor_min_norma": 2.5,
        "espesor_max_norma": 2.9,
        "ovalidad_norma": 2.2,
        "peso_min_teorico": 0.266,
        "peso_max_teorico": 0.345,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 75 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 75,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 2.9,
        "espesor_max_norma": 3.4,
        "ovalidad_norma": 2.6,
        "peso_min_teorico": 0.369,
        "peso_max_teorico": 0.479,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 90 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 90,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 90.0,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.5,
        "espesor_max_norma": 4.1,
        "ovalidad_norma": 3.2,
        "peso_min_teorico": 0.533,
        "peso_max_teorico": 0.691,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 110 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 110,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 110.0,
        "diametro_max": 110.7,
        "espesor_min_norma": 4.2,
        "espesor_max_norma": 4.8,
        "ovalidad_norma": 3.9,
        "peso_min_teorico": 0.783,
        "peso_max_teorico": 1.014,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 125 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 125,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 125.0,
        "diametro_max": 125.8,
        "espesor_min_norma": 4.8,
        "espesor_max_norma": 5.5,
        "ovalidad_norma": 4.4,
        "peso_min_teorico": 1.018,
        "peso_max_teorico": 1.319,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 140 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 140,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 140.0,
        "diametro_max": 140.9,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.2,
        "ovalidad_norma": 4.9,
        "peso_min_teorico": 1.280,
        "peso_max_teorico": 1.658,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 160 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 160,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 160.0,
        "diametro_max": 161.0,
        "espesor_min_norma": 6.2,
        "espesor_max_norma": 7.1,
        "ovalidad_norma": 5.6,
        "peso_min_teorico": 1.678,
        "peso_max_teorico": 2.172,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 180 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 180,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 180.0,
        "diametro_max": 181.1,
        "espesor_min_norma": 6.9,
        "espesor_max_norma": 7.9,
        "ovalidad_norma": 6.3,
        "peso_min_teorico": 2.106,
        "peso_max_teorico": 2.726,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 200 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 200,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 200.0,
        "diametro_max": 201.2,
        "espesor_min_norma": 7.7,
        "espesor_max_norma": 8.8,
        "ovalidad_norma": 7.0,
        "peso_min_teorico": 2.610,
        "peso_max_teorico": 3.379,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 225 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 225,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 225.0,
        "diametro_max": 226.4,
        "espesor_min_norma": 8.6,
        "espesor_max_norma": 9.8,
        "ovalidad_norma": 7.9,
        "peso_min_teorico": 3.275,
        "peso_max_teorico": 4.237,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 250 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 250,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 250.0,
        "diametro_max": 251.5,
        "espesor_min_norma": 9.6,
        "espesor_max_norma": 11.0,
        "ovalidad_norma": 8.8,
        "peso_min_teorico": 4.062,
        "peso_max_teorico": 5.257,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 280 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 280,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 280.0,
        "diametro_max": 281.7,
        "espesor_min_norma": 10.7,
        "espesor_max_norma": 12.2,
        "ovalidad_norma": 9.8,
        "peso_min_teorico": 5.068,
        "peso_max_teorico": 6.556,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 315 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 315,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 315.0,
        "diametro_max": 316.9,
        "espesor_min_norma": 12.1,
        "espesor_max_norma": 13.8,
        "ovalidad_norma": 11.0,
        "peso_min_teorico": 6.447,
        "peso_max_teorico": 8.339,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 355 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 355,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 355.0,
        "diametro_max": 357.1,
        "espesor_min_norma": 13.6,
        "espesor_max_norma": 15.5,
        "ovalidad_norma": 12.4,
        "peso_min_teorico": 8.163,
        "peso_max_teorico": 10.554,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 400 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 400,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 400.0,
        "diametro_max": 402.4,
        "espesor_min_norma": 15.3,
        "espesor_max_norma": 17.4,
        "ovalidad_norma": 14.0,
        "peso_min_teorico": 10.344,
        "peso_max_teorico": 13.385,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 450 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 450,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 450.0,
        "diametro_max": 452.7,
        "espesor_min_norma": 17.2,
        "espesor_max_norma": 19.6,
        "ovalidad_norma": 15.8,
        "peso_min_teorico": 13.067,
        "peso_max_teorico": 16.907,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 500 mm PN6",
        "material": "PEAD",
        "diametro_nominal": 500,
        "presion_nominal": "PN6",
        "sdr": "SDR 26",
        "diametro_min": 500.0,
        "diametro_max": 503.0,
        "espesor_min_norma": 19.1,
        "espesor_max_norma": 21.7,
        "ovalidad_norma": 17.5,
        "peso_min_teorico": 16.126,
        "peso_max_teorico": 20.849,
        "presion_phi": 24,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "N/A"
    },
    {
        "producto": "Tuberia PEAD 20 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 20,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 20.0,
        "diametro_max": 20.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.101,
        "peso_max_teorico": 0.129,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 25 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 25,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 25.0,
        "diametro_max": 25.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.128,
        "peso_max_teorico": 0.163,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 32 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 32,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 32.0,
        "diametro_max": 32.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.3,
        "peso_min_teorico": 0.167,
        "peso_max_teorico": 0.212,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 40 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 40,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 40.0,
        "diametro_max": 40.4,
        "espesor_min_norma": 2.4,
        "espesor_max_norma": 2.8,
        "ovalidad_norma": 1.4,
        "peso_min_teorico": 0.262,
        "peso_max_teorico": 0.334,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 50 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 50,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 50.0,
        "diametro_max": 50.4,
        "espesor_min_norma": 3.0,
        "espesor_max_norma": 3.5,
        "ovalidad_norma": 1.5,
        "peso_min_teorico": 0.413,
        "peso_max_teorico": 0.526,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 63 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 63,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 63.0,
        "diametro_max": 63.4,
        "espesor_min_norma": 3.8,
        "espesor_max_norma": 4.4,
        "ovalidad_norma": 2.2,
        "peso_min_teorico": 0.655,
        "peso_max_teorico": 0.834,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 75 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 75,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 4.5,
        "espesor_max_norma": 5.1,
        "ovalidad_norma": 2.6,
        "peso_min_teorico": 0.925,
        "peso_max_teorico": 1.178,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 90 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 90,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 90.0,
        "diametro_max": 90.6,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.1,
        "ovalidad_norma": 3.2,
        "peso_min_teorico": 1.328,
        "peso_max_teorico": 1.691,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 110 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 110,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 110.0,
        "diametro_max": 110.7,
        "espesor_min_norma": 6.6,
        "espesor_max_norma": 7.4,
        "ovalidad_norma": 3.9,
        "peso_min_teorico": 1.990,
        "peso_max_teorico": 2.535,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 125 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 125,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 125.0,
        "diametro_max": 125.8,
        "espesor_min_norma": 7.4,
        "espesor_max_norma": 8.3,
        "ovalidad_norma": 4.4,
        "peso_min_teorico": 2.531,
        "peso_max_teorico": 3.224,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 140 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 140,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 140.0,
        "diametro_max": 140.9,
        "espesor_min_norma": 8.3,
        "espesor_max_norma": 9.3,
        "ovalidad_norma": 4.9,
        "peso_min_teorico": 3.176,
        "peso_max_teorico": 4.045,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 160 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 160,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 160.0,
        "diametro_max": 161.0,
        "espesor_min_norma": 9.5,
        "espesor_max_norma": 10.6,
        "ovalidad_norma": 5.6,
        "peso_min_teorico": 4.143,
        "peso_max_teorico": 5.278,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 180 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 180,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 180.0,
        "diametro_max": 181.1,
        "espesor_min_norma": 10.6,
        "espesor_max_norma": 11.8,
        "ovalidad_norma": 6.3,
        "peso_min_teorico": 5.215,
        "peso_max_teorico": 6.640,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 200 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 200,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 200.0,
        "diametro_max": 201.2,
        "espesor_min_norma": 11.8,
        "espesor_max_norma": 13.2,
        "ovalidad_norma": 7.0,
        "peso_min_teorico": 6.442,
        "peso_max_teorico": 8.196,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 225 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 225,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 225.0,
        "diametro_max": 226.4,
        "espesor_min_norma": 13.3,
        "espesor_max_norma": 14.8,
        "ovalidad_norma": 7.9,
        "peso_min_teorico": 8.175,
        "peso_max_teorico": 10.407,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 250 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 250,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 250.0,
        "diametro_max": 251.5,
        "espesor_min_norma": 14.8,
        "espesor_max_norma": 16.4,
        "ovalidad_norma": 8.8,
        "peso_min_teorico": 10.093,
        "peso_max_teorico": 12.846,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 280 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 280,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 280.0,
        "diametro_max": 281.7,
        "espesor_min_norma": 16.5,
        "espesor_max_norma": 18.3,
        "ovalidad_norma": 9.8,
        "peso_min_teorico": 12.632,
        "peso_max_teorico": 16.082,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 315 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 315,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 315.0,
        "diametro_max": 316.9,
        "espesor_min_norma": 18.6,
        "espesor_max_norma": 20.6,
        "ovalidad_norma": 11.0,
        "peso_min_teorico": 15.998,
        "peso_max_teorico": 20.379,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 355 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 355,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 355.0,
        "diametro_max": 357.1,
        "espesor_min_norma": 20.9,
        "espesor_max_norma": 23.1,
        "ovalidad_norma": 12.4,
        "peso_min_teorico": 20.279,
        "peso_max_teorico": 25.832,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 400 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 400,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 400.0,
        "diametro_max": 402.4,
        "espesor_min_norma": 23.6,
        "espesor_max_norma": 26.1,
        "ovalidad_norma": 14.0,
        "peso_min_teorico": 25.751,
        "peso_max_teorico": 32.795,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 450 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 450,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 450.0,
        "diametro_max": 452.7,
        "espesor_min_norma": 26.5,
        "espesor_max_norma": 29.3,
        "ovalidad_norma": 15.8,
        "peso_min_teorico": 32.551,
        "peso_max_teorico": 41.446,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 500 mm PN10",
        "material": "PEAD",
        "diametro_nominal": 500,
        "presion_nominal": "PN10",
        "sdr": "SDR 17",
        "diametro_min": 500.0,
        "diametro_max": 503.0,
        "espesor_min_norma": 29.4,
        "espesor_max_norma": 32.5,
        "ovalidad_norma": 17.5,
        "peso_min_teorico": 40.093,
        "peso_max_teorico": 51.050,
        "presion_phi": 35,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 20 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 20,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 20.0,
        "diametro_max": 20.3,
        "espesor_min_norma": 2.0,
        "espesor_max_norma": 2.4,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.126,
        "peso_max_teorico": 0.161,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 25 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 25,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 25.0,
        "diametro_max": 25.3,
        "espesor_min_norma": 2.3,
        "espesor_max_norma": 2.7,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.158,
        "peso_max_teorico": 0.201,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 32 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 32,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 32.0,
        "diametro_max": 32.3,
        "espesor_min_norma": 3.0,
        "espesor_max_norma": 3.5,
        "ovalidad_norma": 1.3,
        "peso_min_teorico": 0.260,
        "peso_max_teorico": 0.331,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 40 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 40,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 40.0,
        "diametro_max": 40.4,
        "espesor_min_norma": 3.7,
        "espesor_max_norma": 4.3,
        "ovalidad_norma": 1.4,
        "peso_min_teorico": 0.398,
        "peso_max_teorico": 0.507,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 50 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 50,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 50.0,
        "diametro_max": 50.4,
        "espesor_min_norma": 4.6,
        "espesor_max_norma": 5.3,
        "ovalidad_norma": 1.5,
        "peso_min_teorico": 0.619,
        "peso_max_teorico": 0.788,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 63 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 63,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 63.0,
        "diametro_max": 63.4,
        "espesor_min_norma": 5.8,
        "espesor_max_norma": 6.6,
        "ovalidad_norma": 2.2,
        "peso_min_teorico": 0.985,
        "peso_max_teorico": 1.254,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 75 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 75,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.7,
        "ovalidad_norma": 2.6,
        "peso_min_teorico": 1.378,
        "peso_max_teorico": 1.755,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 90 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 90,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 90.0,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 3.2,
        "peso_min_teorico": 1.986,
        "peso_max_teorico": 2.529,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 110 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 110,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 110.0,
        "diametro_max": 110.7,
        "espesor_min_norma": 10.0,
        "espesor_max_norma": 11.2,
        "ovalidad_norma": 3.9,
        "peso_min_teorico": 2.964,
        "peso_max_teorico": 3.774,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 125 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 125,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 125.0,
        "diametro_max": 125.8,
        "espesor_min_norma": 11.4,
        "espesor_max_norma": 12.7,
        "ovalidad_norma": 4.4,
        "peso_min_teorico": 3.840,
        "peso_max_teorico": 4.890,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 140 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 140,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 140.0,
        "diametro_max": 140.9,
        "espesor_min_norma": 12.7,
        "espesor_max_norma": 14.1,
        "ovalidad_norma": 4.9,
        "peso_min_teorico": 4.793,
        "peso_max_teorico": 6.098,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 160 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 160,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 160.0,
        "diametro_max": 161.0,
        "espesor_min_norma": 14.6,
        "espesor_max_norma": 16.2,
        "ovalidad_norma": 5.6,
        "peso_min_teorico": 6.273,
        "peso_max_teorico": 7.989,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 180 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 180,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 180.0,
        "diametro_max": 181.1,
        "espesor_min_norma": 16.4,
        "espesor_max_norma": 18.2,
        "ovalidad_norma": 6.3,
        "peso_min_teorico": 7.925,
        "peso_max_teorico": 10.090,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 200 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 200,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 200.0,
        "diametro_max": 201.2,
        "espesor_min_norma": 18.2,
        "espesor_max_norma": 20.2,
        "ovalidad_norma": 7.0,
        "peso_min_teorico": 9.773,
        "peso_max_teorico": 12.441,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 225 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 225,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 225.0,
        "diametro_max": 226.4,
        "espesor_min_norma": 20.5,
        "espesor_max_norma": 22.7,
        "ovalidad_norma": 7.9,
        "peso_min_teorico": 12.404,
        "peso_max_teorico": 15.795,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 250 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 250,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 250.0,
        "diametro_max": 251.5,
        "espesor_min_norma": 22.7,
        "espesor_max_norma": 25.1,
        "ovalidad_norma": 8.8,
        "peso_min_teorico": 15.289,
        "peso_max_teorico": 19.467,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 280 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 280,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 280.0,
        "diametro_max": 281.7,
        "espesor_min_norma": 25.4,
        "espesor_max_norma": 28.1,
        "ovalidad_norma": 9.8,
        "peso_min_teorico": 19.167,
        "peso_max_teorico": 24.394,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 315 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 315,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 315.0,
        "diametro_max": 316.9,
        "espesor_min_norma": 28.6,
        "espesor_max_norma": 31.6,
        "ovalidad_norma": 11.0,
        "peso_min_teorico": 24.269,
        "peso_max_teorico": 30.887,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 355 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 355,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 355.0,
        "diametro_max": 357.1,
        "espesor_min_norma": 32.2,
        "espesor_max_norma": 35.6,
        "ovalidad_norma": 12.4,
        "peso_min_teorico": 30.793,
        "peso_max_teorico": 39.190,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 400 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 400,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 400.0,
        "diametro_max": 402.4,
        "espesor_min_norma": 36.3,
        "espesor_max_norma": 40.1,
        "ovalidad_norma": 14.0,
        "peso_min_teorico": 39.227,
        "peso_max_teorico": 49.907,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 450 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 450,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 450.0,
        "diametro_max": 452.7,
        "espesor_min_norma": 40.9,
        "espesor_max_norma": 45.1,
        "ovalidad_norma": 15.8,
        "peso_min_teorico": 49.638,
        "peso_max_teorico": 63.155,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 500 mm PN16",
        "material": "PEAD",
        "diametro_nominal": 500,
        "presion_nominal": "PN16",
        "sdr": "SDR 11",
        "diametro_min": 500.0,
        "diametro_max": 503.0,
        "espesor_min_norma": 45.4,
        "espesor_max_norma": 50.1,
        "ovalidad_norma": 17.5,
        "peso_min_teorico": 61.233,
        "peso_max_teorico": 77.886,
        "presion_phi": 54,
        "temperatura_phi": 80,
        "tiempo_phi": 165,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 20 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 20,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 20.0,
        "diametro_max": 20.3,
        "espesor_min_norma": 2.3,
        "espesor_max_norma": 2.7,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.125,
        "peso_max_teorico": 0.159,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 25 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 25,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 25.0,
        "diametro_max": 25.3,
        "espesor_min_norma": 2.8,
        "espesor_max_norma": 3.3,
        "ovalidad_norma": 1.2,
        "peso_min_teorico": 0.188,
        "peso_max_teorico": 0.239,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 32 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 32,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 32.0,
        "diametro_max": 32.3,
        "espesor_min_norma": 3.6,
        "espesor_max_norma": 4.2,
        "ovalidad_norma": 1.3,
        "peso_min_teorico": 0.306,
        "peso_max_teorico": 0.390,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 40 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 40,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 40.0,
        "diametro_max": 40.4,
        "espesor_min_norma": 4.5,
        "espesor_max_norma": 5.2,
        "ovalidad_norma": 1.4,
        "peso_min_teorico": 0.477,
        "peso_max_teorico": 0.607,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 50 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 50,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 50.0,
        "diametro_max": 50.4,
        "espesor_min_norma": 5.6,
        "espesor_max_norma": 6.4,
        "ovalidad_norma": 1.5,
        "peso_min_teorico": 0.741,
        "peso_max_teorico": 0.943,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 63 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 63,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 63.0,
        "diametro_max": 63.4,
        "espesor_min_norma": 7.0,
        "espesor_max_norma": 8.0,
        "ovalidad_norma": 2.2,
        "peso_min_teorico": 1.173,
        "peso_max_teorico": 1.494,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 75 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 75,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 8.4,
        "espesor_max_norma": 9.5,
        "ovalidad_norma": 2.6,
        "peso_min_teorico": 1.666,
        "peso_max_teorico": 2.122,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 90 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 90,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 90.0,
        "diametro_max": 90.6,
        "espesor_min_norma": 10.0,
        "espesor_max_norma": 11.3,
        "ovalidad_norma": 3.2,
        "peso_min_teorico": 2.381,
        "peso_max_teorico": 3.031,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 110 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 110,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 110.0,
        "diametro_max": 110.7,
        "espesor_min_norma": 12.3,
        "espesor_max_norma": 13.7,
        "ovalidad_norma": 3.9,
        "peso_min_teorico": 3.578,
        "peso_max_teorico": 4.553,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 125 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 125,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 125.0,
        "diametro_max": 125.8,
        "espesor_min_norma": 13.9,
        "espesor_max_norma": 15.4,
        "ovalidad_norma": 4.4,
        "peso_min_teorico": 4.603,
        "peso_max_teorico": 5.856,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 140 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 140,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 140.0,
        "diametro_max": 140.9,
        "espesor_min_norma": 15.6,
        "espesor_max_norma": 17.3,
        "ovalidad_norma": 4.9,
        "peso_min_teorico": 5.789,
        "peso_max_teorico": 7.365,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 160 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 160,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 160.0,
        "diametro_max": 161.0,
        "espesor_min_norma": 17.8,
        "espesor_max_norma": 19.7,
        "ovalidad_norma": 5.6,
        "peso_min_teorico": 7.533,
        "peso_max_teorico": 9.584,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 180 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 180,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 180.0,
        "diametro_max": 181.1,
        "espesor_min_norma": 20.0,
        "espesor_max_norma": 22.1,
        "ovalidad_norma": 6.3,
        "peso_min_teorico": 9.521,
        "peso_max_teorico": 12.113,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 200 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 200,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 200.0,
        "diametro_max": 201.2,
        "espesor_min_norma": 22.2,
        "espesor_max_norma": 24.6,
        "ovalidad_norma": 7.0,
        "peso_min_teorico": 11.748,
        "peso_max_teorico": 14.945,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 225 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 225,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 225.0,
        "diametro_max": 226.4,
        "espesor_min_norma": 25.0,
        "espesor_max_norma": 27.6,
        "ovalidad_norma": 7.9,
        "peso_min_teorico": 14.860,
        "peso_max_teorico": 18.904,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 250 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 250,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 250.0,
        "diametro_max": 251.5,
        "espesor_min_norma": 27.8,
        "espesor_max_norma": 30.7,
        "ovalidad_norma": 8.8,
        "peso_min_teorico": 18.337,
        "peso_max_teorico": 23.327,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 280 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 280,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 280.0,
        "diametro_max": 281.7,
        "espesor_min_norma": 31.1,
        "espesor_max_norma": 34.4,
        "ovalidad_norma": 9.8,
        "peso_min_teorico": 23.011,
        "peso_max_teorico": 29.273,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 315 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 315,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 315.0,
        "diametro_max": 316.9,
        "espesor_min_norma": 35.0,
        "espesor_max_norma": 38.6,
        "ovalidad_norma": 11.0,
        "peso_min_teorico": 29.136,
        "peso_max_teorico": 37.042,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 355 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 355,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 355.0,
        "diametro_max": 357.1,
        "espesor_min_norma": 39.4,
        "espesor_max_norma": 43.5,
        "ovalidad_norma": 12.4,
        "peso_min_teorico": 37.065,
        "peso_max_teorico": 47.142,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 400 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 400,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 400.0,
        "diametro_max": 402.4,
        "espesor_min_norma": 44.4,
        "espesor_max_norma": 49.0,
        "ovalidad_norma": 14.0,
        "peso_min_teorico": 47.147,
        "peso_max_teorico": 59.948,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 450 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 450,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 450.0,
        "diametro_max": 452.7,
        "espesor_min_norma": 50.0,
        "espesor_max_norma": 55.1,
        "ovalidad_norma": 15.8,
        "peso_min_teorico": 59.638,
        "peso_max_teorico": 75.861,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    },
    {
        "producto": "Tuberia PEAD 500 mm PN21",
        "material": "PEAD",
        "diametro_nominal": 500,
        "presion_nominal": "PN21",
        "sdr": "SDR 9",
        "diametro_min": 500.0,
        "diametro_max": 503.0,
        "espesor_min_norma": 55.5,
        "espesor_max_norma": 61.2,
        "ovalidad_norma": 17.5,
        "peso_min_teorico": 73.570,
        "peso_max_teorico": 93.573,
        "presion_phi": null,
        "temperatura_phi": null,
        "tiempo_phi": null,
        "color_tuberia": "Negro",
        "color_linea": "Azul"
    }
]
