export interface TipoProducto {
  producto: string;
  material: 'PE100' | 'PP' | 'PP-RCT/FV' | 'PEAD' | 'PPR' | 'PP-R' | 'PPR-CT' | 'PPR-CT/FV' | 'PP-RCT' | 'PP-R(R3)' | 'PP-H';
  diametro_nominal: number;
  presion_nominal: string;
  sdr: string;
  diametro_min: number;
  diametro_max: number;
  espesor_min_norma: number;
  espesor_max_norma: number | null;
  ovalidad_norma: number | null;
  peso_min_teorico: number;
  peso_max_teorico: number;
  presion_phi: number | null;
  temperatura_phi: number | null;
  tiempo_phi: number | null;
  color_tuberia?: string;
  color_linea?: string;
}

export const matrizProductos: TipoProducto[] = [
    {
        "producto": "200mm x 6m BETA/FIBRA/BOX",
        "material": "PP-RCT/FV",
        "diametro_nominal": 200,
        "presion_nominal": "PN",
        "sdr": "S",
        "diametro_min": 200.5,
        "diametro_max": 201.3,
        "espesor_min_norma": 27.0,
        "espesor_max_norma": null,
        "ovalidad_norma": null,
        "peso_min_teorico": 8.7185,
        "peso_max_teorico": 9.1538,
        "presion_phi": 47.0,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "SIN LINEA"
    },
    {
        "producto": "200mm x 6m BETA PN-20 S-3,2",
        "material": "PP-RCT",
        "diametro_nominal": 200,
        "presion_nominal": "PN-20",
        "sdr": "S-3,2",
        "diametro_min": 200.1,
        "diametro_max": 201.9,
        "espesor_min_norma": 20.9,
        "espesor_max_norma": 23.4,
        "ovalidad_norma": 4.0,
        "peso_min_teorico": 11.378,
        "peso_max_teorico": 10.74,
        "presion_phi": 47.0,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "ROJO"
    },
    {
        "producto": "90mm R3 PN-10 S-5",
        "material": "PP-R",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "S-5",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.0232,
        "peso_max_teorico": 1.9094,
        "presion_phi": 32,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(R3)",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm R3 PN-16 S-3,2",
        "material": "PP-R(R3)",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "S-3,2",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 12.3,
        "espesor_max_norma": 13.7,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.974,
        "peso_max_teorico": 2.808,
        "presion_phi": 47,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(R3)",
        "color_linea": "ROJO"
    },
    {
        "producto": "90mm R3 PN-16 S-3,2",
        "material": "PP-R",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "S-3,2",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 12.3,
        "espesor_max_norma": 13.7,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.8639,
        "peso_max_teorico": 2.7207,
        "presion_phi": 50,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(R3)",
        "color_linea": "ROJO"
    },
    {
        "producto": "90mm R3 PN-20 S-2,5",
        "material": "PP-R(R3)",
        "diametro_nominal": 90,
        "presion_nominal": "PN-20",
        "sdr": "S-2,5",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 15,
        "espesor_max_norma": 16.6,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 3.5477,
        "peso_max_teorico": 3.7028,
        "presion_phi": 64,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "VERDE",
        "color_linea": "ROJO"
    },
    {
        "producto": "90mm x 6m BETA/FIBRA PN-10 S-5",
        "material": "PP-RCT/FV",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "S-5",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1326,
        "peso_max_teorico": 2.2271,
        "presion_phi": 30,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "BLANCO"
    },
    {
        "producto": "90mm x 6m BETA/FIBRA PN-10 S-5 S,2",
        "material": "PP-RCT/FV",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "S-5 S,2",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 12.3,
        "espesor_max_norma": 13.7,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.974,
        "peso_max_teorico": 2.808,
        "presion_phi": 47,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "NARANJA"
    },
    {
        "producto": "90mm x 6m BETA/FIBRA PN-12,5 S-4",
        "material": "PP-RCT/FV",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "S-4",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 10.1,
        "espesor_max_norma": 11.3,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.5217,
        "peso_max_teorico": 2.3832,
        "presion_phi": 38,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "NARANJA"
    },
    {
        "producto": "90mm x 6m BETA/FIBRA PN-16 S-3,2",
        "material": "PP-RCT/FV",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "S-3,2",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 12.3,
        "espesor_max_norma": 13.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 14.6598,
        "peso_max_teorico": 12.747,
        "presion_phi": 47,
        "temperatura_phi": 135,
        "tiempo_phi": 4,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "NARANJA"
    },
    {
        "producto": "90mm x 6m BETA/FIBRA PN-20 S-2,5",
        "material": "PP-RCT/FV",
        "diametro_nominal": 90,
        "presion_nominal": "PN-20",
        "sdr": "S-2,5",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 15.1,
        "espesor_max_norma": 16.6,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 3.4226,
        "peso_max_teorico": 3.2309,
        "presion_phi": 64,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "VERDE"
    },
    {
        "producto": "90mm x 6m BETA PN-10 S-5",
        "material": "PP-RCT",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "S-5",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1014,
        "peso_max_teorico": 1.9832,
        "presion_phi": 30,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(BETA)",
        "color_linea": "NARANJA"
    },
    {
        "producto": "90mm x 6m HDPE PN-10 SDR-17",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "SDR-17",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.1,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.4585,
        "peso_max_teorico": 1.3706,
        "presion_phi": 15.5,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 6m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 6m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "SDR-11",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1256,
        "peso_max_teorico": 2.0124,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 6m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-6",
        "sdr": "SDR-27,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.3,
        "espesor_max_norma": 3.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 0.9364,
        "peso_max_teorico": 0.8584,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 6m POLI-ONE PN-10 S-5",
        "material": "PP-R",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "S-5",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.0232,
        "peso_max_teorico": 1.9094,
        "presion_phi": 32,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "ROJO"
    },
    {
        "producto": "90mm x 6m POLI-ONE PN-16 S-3,2",
        "material": "PP-R",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "S-3,2",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 12.3,
        "espesor_max_norma": 13.7,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.8639,
        "peso_max_teorico": 2.7207,
        "presion_phi": 42,
        "temperatura_phi": 150,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "SIN LINEA"
    },
    {
        "producto": "90mm x 6m POLI-ONE/BETA PN-16 S-3,2",
        "material": "PP-RCT",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "S-3,2",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 12.3,
        "espesor_max_norma": 13.7,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.9168,
        "peso_max_teorico": 2.7207,
        "presion_phi": 47,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "SIN LINEA (BETA)"
    },
    {
        "producto": "90mm x 6m R3 PN-10 S-5,1",
        "material": "PP-R",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "S-5,1",
        "diametro_min": 90.1,
        "diametro_max": 90.9,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.0232,
        "peso_max_teorico": 2.137,
        "presion_phi": 30,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(R3)",
        "color_linea": "ROJO"
    },
    {
        "producto": "90mm x 100m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "SDR-11",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1256,
        "peso_max_teorico": 2.0124,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 100m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-20",
        "sdr": "SDR-9",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 10.1,
        "espesor_max_norma": 11.3,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.5548,
        "peso_max_teorico": 2.4211,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 100m SMARTCOLORS PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 100m SMARTCOLORS PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN 16",
        "sdr": "SDR-11",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1256,
        "peso_max_teorico": 2.0124,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 100m SMARTCOLORS PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-6",
        "sdr": "SDR-27,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.3,
        "espesor_max_norma": 3.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 0.9364,
        "peso_max_teorico": 0.8584,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m HDPE PN-10 SDR-17",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "SDR-17",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.1,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.4585,
        "peso_max_teorico": 1.3706,
        "presion_phi": 15.5,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "SDR-11",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1256,
        "peso_max_teorico": 2.0124,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-20",
        "sdr": "SDR-9",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 10.1,
        "espesor_max_norma": 11.3,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.5548,
        "peso_max_teorico": 2.4211,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-6",
        "sdr": "SDR-27,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.3,
        "espesor_max_norma": 3.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 0.9364,
        "peso_max_teorico": 0.8584,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m SMARTCOLORS PN-10 SDR-17",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "SDR-17",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.1,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.4585,
        "peso_max_teorico": 1.3706,
        "presion_phi": 15.5,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m SMARTCOLORS PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 3,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 150m SMARTCOLORS PN-10 SDR-17",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "SDR-17",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.1,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.4585,
        "peso_max_teorico": 1.3706,
        "presion_phi": 15.5,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 150m SMARTCOLORS PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 150m SMARTCOLORS PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "SDR-11",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1256,
        "peso_max_teorico": 2.0124,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 150m SMARTCOLORS PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-20",
        "sdr": "SDR-9",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 10.1,
        "espesor_max_norma": 11.3,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.5548,
        "peso_max_teorico": 2.4211,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 200m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "SDR-11",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1256,
        "peso_max_teorico": 2.0124,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 50m HDPE PN-10 SDR-17",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "SDR-17",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.1,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.4585,
        "peso_max_teorico": 1.3706,
        "presion_phi": 15.5,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 50m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 50m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-16",
        "sdr": "SDR-11",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 8.2,
        "espesor_max_norma": 9.2,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.1256,
        "peso_max_teorico": 2.0124,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 50m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-20",
        "sdr": "SDR-9",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 10.1,
        "espesor_max_norma": 11.3,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 2.5548,
        "peso_max_teorico": 2.4211,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 50m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-6",
        "sdr": "SDR-27,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.3,
        "espesor_max_norma": 3.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 0.9364,
        "peso_max_teorico": 0.8584,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 50m SMARTCOLORS PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 50m SMARTCOLORS PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-6",
        "sdr": "SDR-27,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.3,
        "espesor_max_norma": 3.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 0.9364,
        "peso_max_teorico": 0.8584,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 12m SMARTCOLORS PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-6",
        "sdr": "SDR-27,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.3,
        "espesor_max_norma": 3.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 0.9364,
        "peso_max_teorico": 0.8584,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 6m SMARTCOLORS PN-10 SDR-17",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-10",
        "sdr": "SDR-17",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 5.4,
        "espesor_max_norma": 6.1,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.4585,
        "peso_max_teorico": 1.3706,
        "presion_phi": 15.5,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 6m SMARTCOLORS PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-12,5",
        "sdr": "SDR-13,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 6.7,
        "espesor_max_norma": 7.5,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 1.7722,
        "peso_max_teorico": 1.6744,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "90mm x 6m SMARTCOLORS PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 90,
        "presion_nominal": "PN-6",
        "sdr": "SDR-27,6",
        "diametro_min": 90,
        "diametro_max": 90.6,
        "espesor_min_norma": 3.3,
        "espesor_max_norma": 3.9,
        "ovalidad_norma": 1.8,
        "peso_min_teorico": 0.9364,
        "peso_max_teorico": 0.8584,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 6m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-12,5 SDR-13,6",
        "sdr": "SDR-13,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 5.6,
        "espesor_max_norma": 6.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.236990,
        "peso_max_teorico": 1.166005,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 6m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 SDR-11",
        "sdr": "SDR-11",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.6,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.469807,
        "peso_max_teorico": 1.391381,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 6m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-20 SDR-9",
        "sdr": "SDR-9",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 8.4,
        "espesor_max_norma": 9.4,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.771299,
        "peso_max_teorico": 1.678442,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 6m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-6 SDR-27,6",
        "sdr": "SDR-27,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 2.8,
        "espesor_max_norma": 3.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 0.660678,
        "peso_max_teorico": 0.606524,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 6m POLI-ONE PN-10 S-5",
        "material": "PP-R",
        "diametro_nominal": 75,
        "presion_nominal": "PN-10 S-5",
        "sdr": "S-5",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.6,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.395981,
        "peso_max_teorico": 1.3205,
        "presion_phi": 32,
        "temperatura_phi": 135,
        "tiempo_phi": 1,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "ROJO"
    },
    {
        "producto": "75mm x 6m POLI-ONE PN-16 S-3,2",
        "material": "PP-R",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 S-3,2",
        "sdr": "S-3,2",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 10.3,
        "espesor_max_norma": 11.5,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.989525,
        "peso_max_teorico": 1.8892,
        "presion_phi": 47,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "ROJO"
    },
    {
        "producto": "75mm x 6m POLI-ONE PN-20 S-2,5",
        "material": "PP-R",
        "diametro_nominal": 75,
        "presion_nominal": "PN-20 S-2,5",
        "sdr": "S-2,5",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 12.7,
        "espesor_max_norma": 14.1,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 2.361284,
        "peso_max_teorico": 2.2531,
        "presion_phi": 64,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "VERDE"
    },
    {
        "producto": "75mm x 6m POLI-ONE/BETA PN-16 S-3,2",
        "material": "PP-RCT",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 S-3,2",
        "sdr": "S-3,2",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 10.3,
        "espesor_max_norma": 11.5,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.989525,
        "peso_max_teorico": 1.8892,
        "presion_phi": 47,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "ROJO"
    },
    {
        "producto": "75mm x 6m PP-H PN-16 S-3,2",
        "material": "PP-H",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 S 3,2",
        "sdr": "S-3,2",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 10.3,
        "espesor_max_norma": 11.5,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.998357,
        "peso_max_teorico": 1.8976,
        "presion_phi": 65.8,
        "temperatura_phi": 150,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(PP-H)",
        "color_linea": "SIN LINEA"
    },
    {
        "producto": "75mm x 6m R3 PN-10 S-5",
        "material": "PP-R",
        "diametro_nominal": 75,
        "presion_nominal": "PN-10 S-5",
        "sdr": "S-5",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.6,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.395981,
        "peso_max_teorico": 1.3205,
        "presion_phi": 32,
        "temperatura_phi": 135,
        "tiempo_phi": 1,
        "color_tuberia": "GRIS(R3)",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 6m R3 PN-16 S-3,2",
        "material": "PP-R",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 S-3,2",
        "sdr": "S-3,2",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 10.3,
        "espesor_max_norma": 11.5,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.998357,
        "peso_max_teorico": 1.8976,
        "presion_phi": 50,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(R3)",
        "color_linea": "ROJO"
    },
    {
        "producto": "75mm x 6m R3 PN-20 S-2,5",
        "material": "PP-R",
        "diametro_nominal": 75,
        "presion_nominal": "PN-20 S-2,5",
        "sdr": "S-2,5",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 12.7,
        "espesor_max_norma": 14.1,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 2.361284,
        "peso_max_teorico": 2.2531,
        "presion_phi": 64,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(R3)",
        "color_linea": "VERDE"
    },
    {
        "producto": "75mm x 6m SMART PIPE/PP-RCT PN-16 S-3,2",
        "material": "PP-RCT",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 S-3,2",
        "sdr": "S-3,2",
        "diametro_min": 75.1,
        "diametro_max": 75.7,
        "espesor_min_norma": 10.3,
        "espesor_max_norma": 11.5,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.989525,
        "peso_max_teorico": 1.8892,
        "presion_phi": 47,
        "temperatura_phi": 135,
        "tiempo_phi": 2,
        "color_tuberia": "GRIS(P1)",
        "color_linea": "ROJO"
    },
    {
        "producto": "75mm x 12m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-12,5 SDR-13,6",
        "sdr": "SDR-13,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 5.6,
        "espesor_max_norma": 6.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.236990,
        "peso_max_teorico": 1.166005,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 12m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 SDR-11",
        "sdr": "SDR-11",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.6,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.469807,
        "peso_max_teorico": 1.391381,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 12m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-20 SDR-9",
        "sdr": "SDR-9",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 8.4,
        "espesor_max_norma": 9.4,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.771299,
        "peso_max_teorico": 1.678442,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 12m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-6 SDR-27,6",
        "sdr": "SDR-27,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 2.8,
        "espesor_max_norma": 3.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 0.660678,
        "peso_max_teorico": 0.606524,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 50m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-12,5 SDR-13,6",
        "sdr": "SDR-13,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 5.6,
        "espesor_max_norma": 6.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.236990,
        "peso_max_teorico": 1.166005,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 50m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 SDR-11",
        "sdr": "SDR-11",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.6,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.469807,
        "peso_max_teorico": 1.391381,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 50m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-20 SDR-9",
        "sdr": "SDR-9",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 8.4,
        "espesor_max_norma": 9.4,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.771299,
        "peso_max_teorico": 1.678442,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 50m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-6 SDR-27,6",
        "sdr": "SDR-27,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 2.8,
        "espesor_max_norma": 3.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 0.660678,
        "peso_max_teorico": 0.606524,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 100m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-12,5 SDR-13,6",
        "sdr": "SDR-13,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 5.6,
        "espesor_max_norma": 6.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.236990,
        "peso_max_teorico": 1.166005,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 100m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 SDR-11",
        "sdr": "SDR-11",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.6,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.469807,
        "peso_max_teorico": 1.391381,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 100m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-20 SDR-9",
        "sdr": "SDR-9",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 8.4,
        "espesor_max_norma": 9.4,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.771299,
        "peso_max_teorico": 1.678442,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 100m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-6 SDR-27,6",
        "sdr": "SDR-27,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 2.8,
        "espesor_max_norma": 3.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 0.660678,
        "peso_max_teorico": 0.606524,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 150m HDPE PN-12,5 SDR-13,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-12,5 SDR-13,6",
        "sdr": "SDR-13,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 5.6,
        "espesor_max_norma": 6.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.236990,
        "peso_max_teorico": 1.166005,
        "presion_phi": 19.7,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 150m HDPE PN-16 SDR-11",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-16 SDR-11",
        "sdr": "SDR-11",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 6.8,
        "espesor_max_norma": 7.6,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.469807,
        "peso_max_teorico": 1.391381,
        "presion_phi": 24.8,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 150m HDPE PN-20 SDR-9",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-20 SDR-9",
        "sdr": "SDR-9",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 8.4,
        "espesor_max_norma": 9.4,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 1.771299,
        "peso_max_teorico": 1.678442,
        "presion_phi": 31,
        "temperatura_phi": 110,
        "tiempo_phi": 2,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    },
    {
        "producto": "75mm x 150m HDPE PN-6 SDR-27,6",
        "material": "PE100",
        "diametro_nominal": 75,
        "presion_nominal": "PN-6 SDR-27,6",
        "sdr": "SDR-27,6",
        "diametro_min": 75.0,
        "diametro_max": 75.5,
        "espesor_min_norma": 2.8,
        "espesor_max_norma": 3.3,
        "ovalidad_norma": 1.6,
        "peso_min_teorico": 0.660678,
        "peso_max_teorico": 0.606524,
        "presion_phi": 9.3,
        "temperatura_phi": 110,
        "tiempo_phi": 1,
        "color_tuberia": "NEGRO",
        "color_linea": "AZUL"
    }
]
