# Generated by Django 5.2.5 on 2025-08-21 16:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('tipo', models.CharField(choices=[('materiales', 'Materiales'), ('equipos', 'Equipos'), ('servicios', 'Servicios'), ('calibracion', 'Calibración'), ('mantenimiento', 'Mantenimiento'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('evaluacion', 'En Evaluación')], default='activo', max_length=20, verbose_name='Estado')),
                ('categoria', models.CharField(choices=[('a', 'Categoría A - Crítico'), ('b', 'Categoría B - Importante'), ('c', 'Categoría C - Estándar')], default='c', max_length=1, verbose_name='Categoría')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('contacto_principal', models.CharField(max_length=200, verbose_name='Contacto Principal')),
                ('cargo_contacto', models.CharField(max_length=100, verbose_name='Cargo del Contacto')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono del Contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email del Contacto')),
                ('productos_servicios', models.TextField(verbose_name='Productos/Servicios')),
                ('capacidad_produccion', models.CharField(blank=True, max_length=200, verbose_name='Capacidad de Producción')),
                ('certificaciones', models.JSONField(blank=True, default=list, verbose_name='Certificaciones')),
                ('experiencia_anos', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('calificacion_general', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación General')),
                ('fecha_ultima_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Última Evaluación')),
                ('fecha_proxima_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima Evaluación')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Límite de Crédito')),
                ('condiciones_pago', models.CharField(blank=True, max_length=200, verbose_name='Condiciones de Pago')),
                ('certificado_camara_comercio', models.FileField(blank=True, null=True, upload_to='proveedores/certificados/', verbose_name='Certificado Cámara de Comercio')),
                ('certificado_rut', models.FileField(blank=True, null=True, upload_to='proveedores/certificados/', verbose_name='Certificado RUT')),
                ('otros_documentos', models.JSONField(blank=True, default=list, verbose_name='Otros Documentos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de Evaluación')),
                ('calificacion_calidad', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Calidad')),
                ('calificacion_entrega', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Entrega')),
                ('calificacion_precio', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Precio')),
                ('calificacion_servicio', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Servicio')),
                ('calificacion_tecnico', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Aspecto Técnico')),
                ('calificacion_financiero', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Aspecto Financiero')),
                ('calificacion_promedio', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación Promedio')),
                ('conclusion', models.TextField(verbose_name='Conclusión')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('acciones_mejora', models.JSONField(blank=True, default=list, verbose_name='Acciones de Mejora')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('reporte_evaluacion', models.FileField(blank=True, null=True, upload_to='proveedores/evaluaciones/', verbose_name='Reporte de Evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Evaluación de Proveedor',
                'verbose_name_plural': 'Evaluaciones de Proveedores',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documental', 'Documental'), ('in_situ', 'In Situ'), ('seguimiento', 'Seguimiento'), ('certificacion', 'Certificación')], max_length=20, verbose_name='Tipo')),
                ('fecha_auditoria', models.DateField(verbose_name='Fecha de Auditoría')),
                ('fecha_proxima_auditoria', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima Auditoría')),
                ('equipo_auditor', models.JSONField(blank=True, default=list, verbose_name='Equipo Auditor')),
                ('alcance', models.TextField(verbose_name='Alcance')),
                ('objetivos', models.TextField(verbose_name='Objetivos')),
                ('resultado', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No Conforme'), ('conforme_con_observaciones', 'Conforme con Observaciones')], max_length=30, verbose_name='Resultado')),
                ('hallazgos', models.JSONField(blank=True, default=list, verbose_name='Hallazgos')),
                ('no_conformidades', models.JSONField(blank=True, default=list, verbose_name='No Conformidades')),
                ('observaciones', models.JSONField(blank=True, default=list, verbose_name='Observaciones')),
                ('acciones_correctivas', models.JSONField(blank=True, default=list, verbose_name='Acciones Correctivas')),
                ('fecha_limite_acciones', models.DateField(blank=True, null=True, verbose_name='Fecha Límite Acciones')),
                ('plan_auditoria', models.FileField(blank=True, null=True, upload_to='proveedores/auditorias/', verbose_name='Plan de Auditoría')),
                ('reporte_auditoria', models.FileField(blank=True, null=True, upload_to='proveedores/auditorias/', verbose_name='Reporte de Auditoría')),
                ('evidencias', models.JSONField(blank=True, default=list, verbose_name='Evidencias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('auditor_lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_proveedores_lideradas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Líder')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Auditoría de Proveedor',
                'verbose_name_plural': 'Auditorías de Proveedores',
                'ordering': ['-fecha_auditoria'],
            },
        ),
    ]
