# Generated by Django 5.2.5 on 2025-08-21 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('tipo', models.CharField(choices=[('analitico', 'Analítico'), ('medicion', 'Medición'), ('control', 'Control'), ('auxiliar', 'Auxiliar'), ('computacional', 'Computacional')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento'), ('calibracion', 'En Calibración'), ('fuera_servicio', 'Fuera de Servicio'), ('retirado', 'Retirado')], default='activo', max_length=20, verbose_name='Estado')),
                ('criticidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Criticidad')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('especificaciones', models.JSONField(blank=True, default=dict, verbose_name='Especificaciones Técnicas')),
                ('rango_medicion', models.CharField(blank=True, max_length=200, verbose_name='Rango de Medición')),
                ('resolucion', models.CharField(blank=True, max_length=100, verbose_name='Resolución')),
                ('incertidumbre', models.CharField(blank=True, max_length=100, verbose_name='Incertidumbre')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('fecha_ultima_calibracion', models.DateField(blank=True, null=True, verbose_name='Fecha Última Calibración')),
                ('fecha_proxima_calibracion', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima Calibración')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Último Mantenimiento')),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Mantenimiento')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('contacto_proveedor', models.CharField(blank=True, max_length=200, verbose_name='Contacto Proveedor')),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de Adquisición')),
                ('manual_usuario', models.FileField(blank=True, null=True, upload_to='equipos/manuales/', verbose_name='Manual de Usuario')),
                ('certificado_calibracion', models.FileField(blank=True, null=True, upload_to='equipos/certificados/', verbose_name='Certificado de Calibración')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ControlEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicio_uso', 'Inicio de Uso'), ('fin_uso', 'Fin de Uso'), ('verificacion', 'Verificación'), ('ajuste', 'Ajuste'), ('limpieza', 'Limpieza'), ('incidente', 'Incidente')], max_length=20, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_medicion', models.JSONField(blank=True, default=dict, verbose_name='Datos de Medición')),
                ('condiciones_ambientales', models.JSONField(blank=True, default=dict, verbose_name='Condiciones Ambientales')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_control', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_control', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Evento de Control',
                'verbose_name_plural': 'Eventos de Control',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa'), ('verificacion', 'Verificación')], max_length=20, verbose_name='Tipo')),
                ('fecha_calibracion', models.DateField(verbose_name='Fecha de Calibración')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('condicional', 'Condicional')], max_length=20, verbose_name='Resultado')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='equipos/calibraciones/', verbose_name='Certificado')),
                ('patron_utilizado', models.CharField(blank=True, max_length=200, verbose_name='Patrón Utilizado')),
                ('incertidumbre_medicion', models.CharField(blank=True, max_length=100, verbose_name='Incertidumbre de Medición')),
                ('condiciones_ambientales', models.JSONField(blank=True, default=dict, verbose_name='Condiciones Ambientales')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibraciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('calibrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibraciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Calibrado por')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibraciones', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Calibración',
                'verbose_name_plural': 'Calibraciones',
                'ordering': ['-fecha_calibracion'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], max_length=20, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('actividades_realizadas', models.TextField(blank=True, verbose_name='Actividades Realizadas')),
                ('repuestos_utilizados', models.JSONField(blank=True, default=list, verbose_name='Repuestos Utilizados')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('asignado_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.equipo', verbose_name='Equipo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
