# Generated by Django 5.2.5 on 2025-08-21 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('melt_index', 'Melt Index'), ('densidad', 'Densidad'), ('resistencia_traccion', 'Resistencia a la Tracción'), ('presion_hidrostatica', 'Presión Hidrostática'), ('impacto', 'Impacto'), ('dureza', 'Dureza'), ('color', 'Color'), ('dimensiones', 'Dimensiones'), ('otros', 'Otros')], max_length=30, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('resultado', models.JSONField(blank=True, default=dict, verbose_name='Resultado')),
                ('resultado_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Resultado Numérico')),
                ('unidad_resultado', models.CharField(blank=True, max_length=20, verbose_name='Unidad del Resultado')),
                ('especificacion_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Especificación Mínima')),
                ('especificacion_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Especificación Máxima')),
                ('especificacion_objetivo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Especificación Objetivo')),
                ('cumple_especificacion', models.BooleanField(blank=True, null=True, verbose_name='Cumple Especificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('observaciones_rechazo', models.TextField(blank=True, verbose_name='Observaciones de Rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensayos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensayos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensayos_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Ensayo',
                'verbose_name_plural': 'Ensayos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ensayos.ensayo', verbose_name='Ensayo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Ensayo',
                'verbose_name_plural': 'Historial de Ensayos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('tuberia_hdpe', 'Tubería HDPE'), ('tuberia_pp', 'Tubería PP'), ('materia_prima', 'Materia Prima'), ('reprocesado', 'Reprocesado'), ('accesorio', 'Accesorio'), ('agua', 'Agua')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('rechazada', 'Rechazada'), ('archivada', 'Archivada')], default='recibida', max_length=20, verbose_name='Estado')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unidad', models.CharField(default='kg', max_length=20, verbose_name='Unidad')),
                ('temperatura_almacenamiento', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura de Almacenamiento (°C)')),
                ('humedad_almacenamiento', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Humedad de Almacenamiento (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('recibida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibida por')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.AddField(
            model_name='ensayo',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='ensayos.muestra', verbose_name='Muestra'),
        ),
        migrations.CreateModel(
            name='ResultadoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100, verbose_name='Parámetro')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Valor')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad')),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Medición')),
                ('equipo_utilizado', models.CharField(blank=True, max_length=100, verbose_name='Equipo Utilizado')),
                ('condiciones_ambientales', models.JSONField(blank=True, default=dict, verbose_name='Condiciones Ambientales')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_detallados', to='ensayos.ensayo', verbose_name='Ensayo')),
            ],
            options={
                'verbose_name': 'Resultado de Ensayo',
                'verbose_name_plural': 'Resultados de Ensayo',
                'ordering': ['-fecha_medicion'],
            },
        ),
    ]
